app/routes/main.py
from numpy.core.function_base import linspace
import pandas
import os
import shutil
import io
import math

import cv2
import numpy as np

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from pprint import pprint
from flask import (
    after_this_request, Response,
    abort, flash, json, jsonify,
    render_template, request, send_file,
    Blueprint, current_app as app
)
from sqlalchemy import func
from functools import reduce
from datetime import datetime, timedelta
from app import db
from app.models import Sheet
import app.image_proc as ip


bp = Blueprint("main", __name__)


# TODO: should have all file creation and handled in Sheet Model

def get_corners(cnt):
    # get bounding rect corners
    min_rect = cv2.minAreaRect(cnt)
    box = cv2.boxPoints(min_rect)
    pts = box.reshape(4, 2).tolist()
    pts = sorted(pts, key=lambda p: p[1])
    tl_pt, tr_pt = sorted(pts[:2], key=lambda p: p[0])
    bl_pt, br_pt = sorted(pts[-2:], key=lambda p: p[0])
    # print('min area rect points')
    # print('tl_pt', tl_pt, flush=True)
    # print('tr_pt', tr_pt, flush=True)
    # print('bl_pt', bl_pt, flush=True)
    # print('br_pt', br_pt, flush=True)
    c_tl_pt = min(cnt, key=lambda p: ip.distance(p[0], tl_pt))[0]
    c_tr_pt = min(cnt, key=lambda p: ip.distance(p[0], tr_pt))[0]
    c_br_pt = min(cnt, key=lambda p: ip.distance(p[0], br_pt))[0]
    c_bl_pt = min(cnt, key=lambda p: ip.distance(p[0], bl_pt))[0]
    # print('hull points')
    # print('c_tl_pt', c_tl_pt, flush=True)
    # print('c_tr_pt', c_tr_pt, flush=True)
    # print('c_bl_pt', c_bl_pt, flush=True)
    # print('c_br_pt', c_br_pt, flush=True)
    return [c_tl_pt, c_tr_pt, c_br_pt, c_bl_pt]


def ud(image):
    width = image.shape[1]
    height = image.shape[0]
    # k1 = -1.5e-6  # negative to remove barrel distortion
    k1 = -1.5e-6  # negative to remove barrel distortion
    k2 = 0.0
    p1 = 0.0
    p2 = 0.0
    k3 = 0.0
    dist = np.array([
        [k1, k2, p1, p2, k3]
    ])
    # assume unit matrix for camera
    # focal_x = 10.0              # define focal length x
    # focal_y = 10.0              # define focal length y
    focal_x = 10.0              # define focal length x
    focal_y = 10.0              # define focal length y
    center_y = (height / 2.0)     # define center y
    center_x = (width / 2.0)      # define center x
    mtx = np.array([
        [focal_x, 0.0, center_x],
        [0.0, focal_y, center_y],
        [0.0, 0.0, 1.0]
    ])
    dst = cv2.undistort(image, mtx, dist)
    # center = (dst.shape[1] // 2, dst.shape[0] // 2)
    # angle = -50
    # scale = 0.6
    # rot_mat = cv2.getRotationMatrix2D(center, angle, scale)
    # dst = cv2.warpAffine(dst, rot_mat, (dst.shape[1], dst.shape[0]))
    return dst


def pt(image, cnt):
    min_rect = cv2.minAreaRect(cnt)
    box = cv2.boxPoints(min_rect)
    pts = box.reshape(4, 2)
    rect = np.zeros((4, 2), dtype=np.float32)
    # the top-left point has the smallest sum whereas the
    # bottom-right has the largest sum
    s = pts.sum(axis=1)
    rect[0] = pts[np.argmin(s)]
    rect[2] = pts[np.argmax(s)]
    # compute the difference between the points -- the top-right
    # will have the minumum difference and the bottom-left will
    # have the maximum difference
    diff = np.diff(pts, axis=1)
    rect[1] = pts[np.argmin(diff)]
    rect[3] = pts[np.argmax(diff)]
    # # multiply the rectangle by the original ratio
    # rect *= ratio
    # now that we have our rectangle of points, let's compute
    # the width of our new image
    (tl, tr, br, bl) = rect
    widthA = np.sqrt(((br[0] - bl[0]) ** 2) + ((br[1] - bl[1]) ** 2))
    widthB = np.sqrt(((tr[0] - tl[0]) ** 2) + ((tr[1] - tl[1]) ** 2))
    # ...and now for the height of our new image
    heightA = np.sqrt(((tr[0] - br[0]) ** 2) + ((tr[1] - br[1]) ** 2))
    heightB = np.sqrt(((tl[0] - bl[0]) ** 2) + ((tl[1] - bl[1]) ** 2))
    # take the maximum of the width and height values to reach
    # our final dimensions
    maxWidth = max(int(widthA), int(widthB))
    maxHeight = max(int(heightA), int(heightB))
    # construct our destination points which will be used to
    # map the screen to a top-down, "birds eye" view
    dst = np.array([
        [0, 0],
        [maxWidth - 1, 0],
        [maxWidth - 1, maxHeight - 1],
        [0, maxHeight - 1]], dtype=np.float32)
    # calculate the perspective transform matrix and warp
    # the perspective to grab the screen
    M = cv2.getPerspectiveTransform(rect, dst)
    warp = cv2.warpPerspective(image, M, (maxWidth, maxHeight))
    return warp


def other(image, corners):
    from scipy.interpolate import griddata
    n_image_w = int(ip.distance(corners[0], corners[1]))
    n_image_h = int(ip.distance(corners[1], corners[2]))
    grid_x, grid_y = np.mgrid[
        0:n_image_w-1:np.complex(0, n_image_w),
        0:n_image_h-1:np.complex(0, n_image_h)]
    source = np.array([corners[0], corners[3], corners[1], corners[2], ])
    print(source, flush=True)
    destination = np.array([
        [0, 0], [0, n_image_h-1],
        [n_image_w-1, 0], [n_image_w-1, n_image_h-1] ])
    grid_z = griddata(destination, source, (grid_x, grid_y), method='cubic')
    # grid_z = griddata(destination, source, (grid_y, grid_x), method='cubic')
    map_x = np.append([], [ar[:, 1] for ar in grid_z])\
        .reshape(n_image_w, n_image_h)
    map_y = np.append([], [ar[:, 0] for ar in grid_z])\
        .reshape(n_image_w, n_image_h)
    map_x_32 = map_x.astype('float32')
    map_y_32 = map_y.astype('float32')
    image = cv2.remap(image, map_x_32, map_y_32, cv2.INTER_CUBIC)


def segment_contour_sides(image, cnt):
    corners = get_corners(cnt)
    print('corners', corners, flush=True)
    for x, y in corners:
        image = cv2.circle(image, (int(x), int(y)), 1, (0, 0, 255), 10)
    cnt_indexes = [None] * len(corners)
    for i, [[x, y]] in enumerate(cnt):
        for j, (cx, cy) in enumerate(corners):
            if cx == x and cy == y:
                cnt_indexes[j] = i
    cnt_indexes = sorted(cnt_indexes)
    left = cnt[cnt_indexes[0]:cnt_indexes[1]]
    bottom = cnt[cnt_indexes[1]:cnt_indexes[2]]
    right = cnt[cnt_indexes[2]:cnt_indexes[3]]
    top = np.concatenate((
        np.flip(cnt[cnt_indexes[3]:], axis=0),
        cnt[:cnt_indexes[0]]))
    left_color = (255, 0, 0)
    bottom_color = (0, 255, 0)
    right_color = (0, 0, 255)
    top_color = (255, 255, 0)
    for [[x, y]] in left:
        image = cv2.circle(image, (int(x), int(y)), 1, left_color, 10)
    for [[x, y]] in bottom:
        image = cv2.circle(image, (int(x), int(y)), 1, bottom_color, 10)
    for [[x, y]] in right:
        image = cv2.circle(image, (int(x), int(y)), 1, right_color, 10)
    for [[x, y]] in top:
        image = cv2.circle(image, (int(x), int(y)), 1, top_color, 10)
    tlc, trc, brc, blc = corners


@bp.route("/sheets/<int:sheet_id>/debug", methods=["GET"])
def sheet_debug(sheet_id):
    sheet = Sheet.query.get(sheet_id) or abort(404)
    image = cv2.imread(sheet.filepath)

    image = ud(image)

    vig_rm_image = ip.remove_vignette(image)
    mask = ip.sheet_mask(vig_rm_image)
    sheet_mask_image = cv2.bitwise_and(vig_rm_image, vig_rm_image, mask=mask)
    # mask out area surrounding metal sheet
    metal_mask_image = ip.not_sheet_mask(sheet_mask_image)
    metal_mask_image = cv2.bitwise_and(
        metal_mask_image, metal_mask_image, mask=mask)
    # get metal sheet contour
    cnts, _ = cv2.findContours(
        metal_mask_image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    metal_cnt = max(cnts, key=cv2.contourArea)
    metal_hull = cv2.convexHull(metal_cnt)

    # mask out all but metal sheet
    metal_mask = np.zeros(metal_mask_image.shape[:2], np.uint8)
    metal_mask = cv2.drawContours(metal_mask, [metal_hull], 0, [255], -1)
    image = cv2.bitwise_and(image, image, mask=metal_mask)

    # find cuts
    cuts = ip.get_cuts(image)
    metal_mask = cv2.drawContours(metal_mask, cuts, -1, [0], -1)
    image = cv2.bitwise_and(image, image, mask=metal_mask)

    metal_cnt = ip.scale_contour(metal_cnt, (0.99, 0.99))
    image = pt(image, metal_cnt)
    metal_mask = pt(metal_mask, metal_cnt)

    cut_masks = cv2.bitwise_not(metal_mask)
    cnts, _ = cv2.findContours(
        cut_masks, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    hulls = [cv2.convexHull(cnt) for cnt in cnts]
    image = cv2.drawContours(image, hulls, -1, [0, 0, 255], -1)


    succ, buffer = cv2.imencode('.jpg', ip.scale_image(image, 0.3))
    if not succ:
        abort(500)
    return Response(buffer.tobytes(), mimetype='image/jpeg')


@bp.route("/sheets/<int:sheet_id>/grid", methods=["GET"])
def sheet_grid(sheet_id):
    sheet = Sheet.query.get(sheet_id) or abort(404)
    image = cv2.imread(sheet.filepath)

    # calibration = Sheet.get_calibration()
    # if calibration is not None:
    #     image = ip.undistort(image, calibration)
    image = ud(image)

    vig_rm_image = ip.remove_vignette(image)
    mask = ip.sheet_mask(vig_rm_image)
    sheet_mask_image = cv2.bitwise_and(vig_rm_image, vig_rm_image, mask=mask)
    # mask out area surrounding metal sheet
    metal_mask_image = ip.not_sheet_mask(sheet_mask_image)
    metal_mask_image = cv2.bitwise_and(
        metal_mask_image, metal_mask_image, mask=mask)
    # get metal sheet contour
    cnts, _ = cv2.findContours(
        metal_mask_image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    metal_cnt = max(cnts, key=cv2.contourArea)
    metal_hull = cv2.convexHull(metal_cnt)

    # mask out all but metal sheet
    metal_mask = np.zeros(metal_mask_image.shape[:2], np.uint8)
    metal_mask = cv2.drawContours(metal_mask, [metal_hull], 0, [255], -1)
    image = cv2.bitwise_and(image, image, mask=metal_mask)

    # find cuts
    cuts = ip.get_cuts(image)
    metal_mask = cv2.drawContours(metal_mask, cuts, -1, [0], -1)
    image = cv2.bitwise_and(image, image, mask=metal_mask)

    metal_cnt = ip.scale_contour(metal_cnt, (0.99, 0.99))
    image = pt(image, metal_cnt)

app/templates/docs.html
{% extends "layouts/main.html" %}


{% block content %}
<main class="mdc-top-app-bar--fixed-adjust">
  <div style="width: 1080px; margin: 1rem auto 0;">
    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
      <h2 class="mdc-typography--headline2">Getting Started</h2>
      <p class="mdc-typography--body1">
        This is the QA analysis of metal waste at DPS. Use this app to
        determine the percent of remaining material after cuts.
      </p>
      <h3 class="mdc-typography--headline3" style="margin: 1rem 0;">
        Upload an image
      </h3>
      <img
        src="{{ url_for('static', filename='images/assets/process_upload_image.png') }}"
        alt="Upload image process"
      />
      <hr>
      <h3 class="mdc-typography--headline3" style="margin: 1rem 0;">
        View an image
      </h3>
      <img
        src="{{ url_for('static', filename='images/assets/process_view_sheet.png') }}"
        alt="View sheet process"
      />
      <hr>
      <h3 class="mdc-typography--headline3" style="margin: 1rem 0;">
        Calibrate Camera
      </h3>
      <img
        src="{{ url_for('static', filename='images/assets/process_calibrate_camera.png') }}"
        alt="Calibrate Camera Process"
      />
    </div>
  </div>
</main>
{% endblock %}

app/templates/graph-example.html
<!--
  Graph with link pointer events, created by JLC. Obsolete
  after 7/8/2020 and can be deleted anytime after that date.
-->
{% extends "layouts/main.html" %}

{% block head %}
<script src="https://code.highcharts.com/highcharts.js"></script>
{% endblock %}

{% block content %}
<main class="mdc-top-app-bar--fixed-adjust">
  <figure id="chart"></figure>
</main>

<script>
  const sheets = {{ sheets | safe }};
  const chart = Highcharts.chart("chart", {
    chart: { type: "line" },
    title: { text: "Sheet Unusage" },
    xAxis: {
      categories: sheets.map(s => s.serial_number),
    },
    plotOptions: {
      line: {
        dataLabels: {
          enabled: true,
          formatter(_options) {
            if (this.series.name === "Unused Percent") {
              return `${this.point.y}%`;
            } else if (this.series.name === "Unused Weight") {
              return `${this.point.y} lbs`;
            }
          },
        },
        events: {
          click(event) {
            window.location.href = `/sheets/${sheets[event.point.index].id}`;
          },
        },
      },
    },
    series: [
      {
        name: "Unused Percent",
        data: sheets.map(s => s.calc_unused_pct),
      },
      {
        name: "Unused Weight",
        data: sheets.map(s => s.weight),
      },
    ],
  });
</script>

{% endblock %}

app/templates/index.html
{% extends "layouts/main.html" %} {% block head %}
<script src="https://code.highcharts.com/highcharts.js"></script>
{% endblock %} {% block content %}

<main class="mdc-top-app-bar--fixed-adjust">
  <div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
      <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6">
        <h1 class="mdc-typography--headline3">
          Dashboard
          {% if start_date and end_date %}
          <span
            class="mdc-typography--overline"
            style="opacity: 0.6"
          >
            {{ start_date }} 00:00:00 - {{ end_date }} 23:59:59
          </span>
          {% elif start_date and not end_date %}
          <span
            class="mdc-typography--overline"
            style="opacity: 0.6"
          >
            {{ start_date }} 00:00:00 - now
          </span>
          {% elif not start_date and end_date %}
          <span
            class="mdc-typography--overline"
            style="opacity: 0.6"
          >
            up to {{ end_date }} 23:59:59
          </span>
          {% else %}
          <span
            class="mdc-typography--overline"
            style="opacity: 0.6"
          >
            Last 30 days
          </span>
          {% endif %}
        </h1>
      </div>

      <div
        class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6"
        style="display: flex; align-items: center; justify-content: flex-end;"
      >
        <span class="mdc-typography--overline">Filter by date: </span>
        <input type="date" name="start_date" id="start_date" value="{{ start_date }}">
        <span>-</span>
        <input type="date" name="end_date" id="end_date" value="{{ end_date }}">
        <button
          class="mdc-button"
          onclick="handleFilterSearch()"
          style="margin-left: 1rem;"
        >
          <div class="mdc-button__ripple"></div>
          <span class="mdc-button__label">Submit</span>
        </button>
      </div>

      <div
        class="mdc-layout-grid__cell mdc-layout-grid__cell--span-3"
        style="text-align: center;"
      >
        <span class="mdc-typography--overline">Total Unused</span>
        <h3 class="mdc-typography--headline3" style="margin: 3rem 0;">
          {{ total_unused_weight | round(2) }}
          <span class="mdc-typography--headline6" style="opacity: 0.6;">
            LBS
          </span>
        </h3>
        <span class="mdc-typography--caption" style="opacity: 0.6;"
          >({{ total_count }} sheets)</span
        >
      </div>
      <div
        class="mdc-layout-grid__cell mdc-layout-grid__cell--span-3"
        style="text-align: center;"
      >
        <span class="mdc-typography--overline">Average Sheet Unused</span>
        <h3 class="mdc-typography--headline3" style="margin: 3rem 0;">
          {{ average_unused_pct | round(2) }}%

          <span class="mdc-typography--headline6" style="opacity: 0.6;">
            / {{ average_unused_weight | round(2) }} lbs
          </span>
        </h3>
        <span class="mdc-typography--caption" style="opacity: 0.6;"
          >({{ total_count }} sheets)</span
        >
      </div>

      <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6">
        <figure id="unused-pcts"></figure>
      </div>
    </div>
  </div>
</main>

<script>
  const startDateEl = document.getElementById("start_date");
  const endDateEl = document.getElementById("end_date");

  function handleFilterSearch() {
    let urlString = "";

    if (startDateEl.value && endDateEl.value) {
      urlString += `?start_date=${startDateEl.value}&end_date=${endDateEl.value}`;
    } else if (startDateEl.value && !endDateEl.value) {
      urlString += `?start_date=${startDateEl.value}`;
    } else if (!startDateEl.value && endDateEl.value) {
      urlString += `?end_date=${endDateEl.value}`;
    }

    window.location.href = urlString;
  }

  const averageUnusedPctChart = Highcharts.chart("unused-pcts", {
    chart: { type: "line" },
    title: { text: "Unused Metal Per Day" },
    yAxis: { title: { text: null } },
    xAxis: { labels: { enabled: null } },
    plotOptions: {
      line: {
        dataLabels: {
          enabled: true,
          formatter(options) {
            if (this.series.name === "Unused Percents") {
              return this.point.y + "%";
            } else if (this.series.name === "Unused Weights") {
              return this.point.y + "lbs";
            }
          }
        },
        enableMouseTracking: false,
      },
    },
    series: [
      {
        name: "Unused Percents",
        data: {{ unused_pcts | safe }},
      },
      {
        name: "Unused Weights",
        data: {{ unused_weights | safe }}
      },
    ],
  });
</script>

{% endblock %}

app/templates/sheet.html
{% extends "layouts/main.html" %}

{% block content %}

<main class="mdc-top-app-bar--fixed-adjust">
  <div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
      <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
        <h2 class="mdc-typography--headline2">
          {{ sheet.serial_number }}
          {% if sheet.calc_unused_pct >= 21: %}
            <span style="color: red;">FAIL</span>
          {% else %}
            <span style="color: green;">PASS</span>
          {% endif %}
        </h2>
        <span id="upload-date" class="mdc-typography--caption" style="opacity: 0.6;"></span>
      </div>

      <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-4">
        <a href="#sheet-lightbox">
          <picture>
            <source srcset="{{ sheet.image_path() }}">
            <img src="{{ sheet.image_path() }}" alt="{{ sheet.id }}" style="width: 100%;">
          </picture>
        </a>
        <span class="mdc-typography--caption">Click image to enlarge.</span>

        <a href="javascript:window.history.back();" class="lightbox" id="sheet-lightbox">
          <p class="mdc-typography--overline" style="margin-top: 1rem; color: white;">Click anywhere to dismiss.</p>
          <picture>
            <source srcset="{{ sheet.image_path() }}">
            <img src="{{ sheet.image_path() }}" alt="{{ sheet.id }}" style="height: 92%;">
          </picture>
        </a>
      </div>

      <!-- This block intentionally left blank -->
      <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2"></div>

      <div id="info" class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6">
        <p class="mdc-typography--overline">Uploaded By: {{ sheet.initials }}</p>
        <p class="mdc-typography--overline">Weight: {{ sheet.weight }} lbs</p>
        <p class="mdc-typography--overline">Cut Date: {{ sheet.cut_date.strftime("%x") }}</p>
        <p class="mdc-typography--overline">Total Area: {{ sheet.total_area | round(2) }} sq.in.</p>
        <p class="mdc-typography--overline">Used Area: {{ sheet.used_area | round(2) }} sq.in.</p>
        <p class="mdc-typography--overline">Unused Area: ~{{ sheet.unused_area | round(2) }} sq.in.</p>
        <p class="mdc-typography--overline">Expected Unused Pct: {{ sheet.exp_unused_pct | round(2) }}%</p>
        <p class="mdc-typography--overline">Calculated Unused Pct: {{ sheet.calc_unused_pct | round(2) }}%</p>
        <p class="mdc-typography--overline">Unused Pct Delta: {{ (sheet.exp_unused_pct - sheet.calc_unused_pct) | abs | round(2) }}%</p>
        <p class="mdc-typography--overline">Ratio: {{ sheet.ratio | round(2) }}</p>
        <p class="mdc-typography--overline">PPI: {{ sheet.ppi | round(2) }}</p>
        <button class="mdc-button mdc-button--raised" onclick="handleDelete({{ sheet.id }})">
          <div class="mdc-button__ripple"></div>
          <span class="mdc-button__label">Delete</span>
        </button>
        <button class="mdc-button mdc-button--raised" onclick="window.location='{{ url_for('main.sheet_grid', sheet_id=sheet.id) }}';">
          <div class="mdc-button__ripple"></div>
          <span class="mdc-button__label">Grid</span>
        </button>
        <button class="mdc-button mdc-button--raised" onclick="window.location='{{ url_for('main.sheet_debug', sheet_id=sheet.id) }}';">
          <div class="mdc-button__ripple"></div>
          <span class="mdc-button__label">Debug</span>
        </button>
      </div>

      <div class="mdc-layout-grid__cell--span-12">
        <h3 class="mdc-typography--headline4">Top 3 Largest Contours</h3>
        <div class="mdc-layout-grid__inner" style="margin-top: 1rem;">
          <div class="mdc-layout-grid__cell--span-4"><picture></picture></div>
          <div class="mdc-layout-grid__cell--span-4"><picture></picture></div>
          <div class="mdc-layout-grid__cell--span-4"><picture></picture></div>
        </div>
      </div>
    </div>
  </div>
</main>

<script>
  function handleDelete(sheetId) {
    return fetch(`/sheets/${sheetId}`, { method: "DELETE" })
      .then((response) => {
        if (!response.ok) {
          throw new Error("Unable to delete sheet.");
        }

        return;
      })
      .then(() => {
        window.location.href = "/sheets";
      });
  }
</script>

{% endblock %}

app/templates/test.html
{% extends "layouts/main.html" %} {% block content %}

<main class="mdc-top-app-bar--fixed-adjust">
  <div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
      <!-- <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-3"></div> -->
      <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
        <canvas id="canvas-cuts" width="1152px" height="576px" style="background: #fff; margin:20px;"></canvas>
      </div>

      <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
        <canvas id="canvas" width="1152px" height="576px" style="background: #fff; margin:20px;"></canvas>
      </div>

    </div>
  </div>
</main>

<script type="text/javascript" language="javascript">
const RECTS = {{ rects }};
const CUTS = {{ cuts }};
const PNT_PXL = 3;


console.log(CUTS)

drawCuts();
drawBoard();

function drawCuts(){
  var canvas = document.getElementById("canvas-cuts");
  var ctx = canvas.getContext("2d");
  CUTS.forEach((cut, i) => {
    ctx.fillStyle = '#f00';
    ctx.beginPath();
    cut.forEach((point, j, arr) => {
      console.log(point);
      if (i == 0) {
        ctx.moveTo(point[0], point[1]);
      }
      if (j+1 < arr.length) {
        let nextPoint = arr[j+1];
        ctx.lineTo(point[0],point[1]);
        ctx.lineTo(nextPoint[0], nextPoint[1]);
      } else {
        ctx.closePath();
        ctx.fill();
      }
    })
  });
}

function drawBoard(){
  var canvas = document.getElementById("canvas");
  var ctx = canvas.getContext("2d");
  let offset = 5
  RECTS.forEach((row, i) => {
    row.forEach((area, j) => {
      let [isMetal, [start, end]] = area;
      ctx.strokeStyle = isMetal ? 'blue' : 'red';
      ctx.beginPath();
      ctx.rect(j*PNT_PXL, i*PNT_PXL, 1, 1)
      ctx.stroke();
    })
  })
}

</script>
{% endblock %}